apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bpdmsawardperiod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmsawardperiod
    spec:
      containers:
        - name: bpdmsawardperiod
          image: cstarregistry.azurecr.io/bpdmsawardperiod
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
