apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bpdmsawardperiod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bpdmsawardperiod
    spec:
      containers:
        - name: bpdmsawardperiod
          image: cstarregistry.azurecr.io/bpdmsawardperiod-sit
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmsawardperiod
            - configMapRef:
                name: jvm
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.9
