apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsawardperiod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmsawardperiod
  template:
    metadata:
      labels:
        app: bpdmsawardperiod
    spec:
      containers:
        - name: bpdmsawardperiod
          image: cstaruatregistry.azurecr.io/bpdmsawardperiod
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmsawardperiod
            - configMapRef:
                name: jvm
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
